apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "envoy-grpc-lb.fullname" . }}
  labels:
    {{- include "envoy-grpc-lb.labels" . | nindent 4 }}
data:
  envoy.yaml: |-
    admin:
      access_log_path: /dev/stdout
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9901
    static_resources:
      listeners:
      - address:
          socket_address:
            address: 0.0.0.0
            port_value: {{ .Values.loadbalancer.port }}
        filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            config:
              codec_type: auto
              stat_prefix: ingress_http
              route_config:
                name: local_route
                virtual_hosts:
                - name: backend
                  domains:
                  - "*"
                  routes:
                  - match:
                      prefix: "/"
                      headers:
                      - name: content-type
                        value: application/grpc
                    route:
                      cluster: target
              http_filters:
              - name: envoy.router
                config: {}
      clusters:
      - name: target
        connect_timeout: 0.25s
        type: strict_dns
        lb_policy: round_robin
        http2_protocol_options: {}
        hosts:
        - socket_address:
            address: {{ .Values.loadbalancer.targetHost }}
            port_value: {{ .Values.loadbalancer.targetPort }}
