apiVersion: v1
kind: Service
metadata:
  name: {{ include "envoy-grpc-lb.fullname" . }}
  labels:
    {{- include "envoy-grpc-lb.labels" . | nindent 4 }}
spec:
  type: ClusterIp
  ports:
    - port: {{ .Values.loadbalancer.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "envoy-grpc-lb.selectorLabels" . | nindent 4 }}
